### ISSUE TITLE
Frames not added

### ISSUE THREAD

**Issue by K232** [warrengalyen/GifMotion#1]
Hi,
unfortunately I do not get this to work :-( I've tried to add jpgs or gif, I tried to add them by filename or by retrieving them first (_Dim im As New System.Drawing.Bitmap(filename)_) . I see the image is loaded correct, but no frames are added to the new gif. In the end, the gif is empty and just 33 bytes. Do you have same example files which I could try to import?
Many thanks!

**Comment by warrengalyen** [comment]
This library is still a work in progress. I meant to review in sooner but have been sidetracked with many other projects. I didn't realize I had left it in a broken state, I apologize for that. The project has been patched and should be fully functional from my tests. I'll push the changes by the time you read this. I plan to revisit this project sometime this week and make more improvements.
