### ISSUE TITLE
无法加载Gif图，缺少代码

### ISSUE THREAD

**Issue by HeiGaoLiangMi** [warrengalyen/GifMotion#2]
没有下面对象
using (GifBitmapDecoder gifDecoder = AnimatedGif.Load("C:\\samplegif.gif")) 
{
    // Do stuff
}

**Comment by warrengalyen** [comment]
My original intention was to add the ability to load animated files but never implemented it because you can easily read these files using the `System.Drawing.Imaging` namespace. I went ahead and added a quick implementation to the AnimatedGif class and usage to the demo project.

**Comment by HeiGaoLiangMi** [comment]
warrengalyen thank you for giving me great help
